### ISSUE TITLE
qitoolchain convert-package and make-package

### ISSUE THREAD

**Issue by Fantomatic** [aldebaran/qibuild#30]
Hey, 
I've got two issue relative to creating package with two kind of things. 
First of them is with convert-package which seem to ask 3 arguments instead of the 2 needed in the --help of qitoolchain convert-package.
usage: qitoolchain convert-package [-h] [-v] [--quiet] [--time-stamp]
                                   [--color {always,never,auto}]
                                   [--title {always,never,auto}] [--home HOME]
                                   [--backtrace] [--pdb] --name NAME [--batch]
                                   PACKAGE_PATH
I put you a copy of the error. 

qitoolchain convert-package --name libxml2 libxml2-2.7.7-1.x86_64.rpm  --backtrace
Converting libxml2-2.7.7-1.x86_64.rpm into a qiBuild package
Traceback (most recent call last):  
  File "/usr/bin/qitoolchain", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/qisys/main.py", line 39, in main
    qisys.script.root_command_main(script_name, parser, modules)
  File "/usr/lib/python2.7/site-packages/qisys/script.py", line 250, in root_command_main
    main_wrapper(module, pargs)
  File "/usr/lib/python2.7/site-packages/qisys/script.py", line 135, in main_wrapper
    module.do(args)
  File "/usr/lib/python2.7/site-packages/qitoolchain/actions/convert_package.py", line 36, in do
    res = convert_package(package_path, name, interactive=interactive)
  File "/usr/lib/python2.7/site-packages/qitoolchain/convert.py", line 14, in convert_package
    package = open_package(package_path)
  File "/usr/lib/python2.7/site-packages/qitoolchain/binary_package/__init__.py", line 80, in open_package
    package = generator(package_path)
TypeError: __init__() takes exactly 3 arguments (2 given)

  
For the second issue, it's relative to the make-package which is about creating package from a directory. I don't have any idea about what should i put in the package.xml and i would like to know where i can find this information. 
Thanks in advance

**Comment by dmerejkowsky** [comment]
I'll open a bug for the first issue, but there's no support for rpm packages in qitoolchain (yet, feel free to add some :)

For the second issue, you can find documentation here:
http://doc.aldebaran.com/qibuild/beginner/qitoolchain/tutorial.html
